# Generated by Django 5.1.1 on 2024-09-21 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hallbooking_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercontact',
            old_name='phone_number',
            new_name='number',
        ),
    ]
