# Generated by Django 5.1.1 on 2024-09-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hallbooking_app', '0002_rename_phone_number_usercontact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='event_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='event_details',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='event_type',
            field=models.CharField(default='wedding', max_length=50),
            preserve_default=False,
        ),
    ]
